### ISSUE TITLE
Invalid literal for float(): FREE

### ISSUE THREAD

**Issue by azuravian** [SenorSmartyPants/Comixology-Scraper#6]
When the scraper grabs info on a comic with a price of "FREE", it fails because it is trying to assign a float to the price field.

**Comment by SenorSmartyPants** [comment]
Could you provide a url to a free comic?

**Comment by azuravian** [comment]
https://www.comixology.com/The-Walking-Dead-1/digital-comic/60

I have worked around this, for now, by changing 
`if overwritable(book.BookPrice):`   
to    
`if overwritable(book.BookPrice) and type(CMXData.get('price')) != str:`

**Comment by SenorSmartyPants** [comment]
Pushed change to ComicRack branch in 00b121c
